# ==============================================================
# UPPTIME CONFIGURATION - LIFETIME/LIFETRIAL STATUS PAGE
# ==============================================================

# Informações do proprietário
owner: contato-lifetimepc
repo: upptime-status

# Sites e APIs para monitorar
sites:
  # ============ LIFETRIAL ============
  - name: LifeTrial App
    url: https://lifetrial.lifetimepc.com.br
    icon: https://lifetrial.lifetimepc.com.br/logo.png
    
  - name: LifeTrial API
    url: https://lifetrial.lifetimepc.com.br/api/health
    expectedStatusCodes:
      - 200
      - 201
    
  - name: LifeTrial Backend
    url: https://api.lifetrial.lifetimepc.com.br/health
    expectedStatusCodes:
      - 200

  # ============ LIFETIME PRINCIPAL ============
  - name: LifeTime Website
    url: https://www.lifetimepc.com.br
    
  - name: LifeTime API Clinical Trials
    url: https://www.lifetimepc.com.br/api/clinical-trials/studies/find?size=1
    expectedStatusCodes:
      - 200

  # ============ SERVIÇOS AUXILIARES ============
  - name: LifeTime Pesquisa Clínica
    url: https://lifetimepc.com.br
    
# Configurações de status
status-website:
  cname: status.lifetimepc.com.br
  logoUrl: https://www.lifetimepc.com.br/logo.png
  name: LifeTime Status
  introTitle: "**Status dos Serviços LifeTime**"
  introMessage: Monitoramento em tempo real de todos os serviços LifeTime e LifeTrial. Esta página é atualizada automaticamente a cada 5 minutos.
  navbar:
    - title: Status
      href: /
    - title: LifeTime
      href: https://www.lifetimepc.com.br
    - title: LifeTrial
      href: https://lifetrial.lifetimepc.com.br
  theme: dark
  
# Configurações de incidentes
i18n:
  activeIncidents: Incidentes Ativos
  allSystemsOperational: Todos os sistemas operacionais
  incidentReport: "Relatório de Incidente #$NUMBER"
  pastIncidents: Incidentes Anteriores
  scheduledMaintenance: Manutenção Programada
  overallUptime: Uptime geral
  overallUptimeTitle: Uptime nos últimos 90 dias
  liveStatus: Status ao vivo
  
# Notificações (opcional - configure depois)
notifications:
  # Slack
  # - type: slack
  #   channel: monitoring
  #   url: $SLACK_WEBHOOK_URL
  
  # Email (via SMTP)
  # - type: email
  #   to: suporte@lifetimepc.com.br

# Configurações de commits
commitMessages:
  statusChange: "🔔 $SITE_NAME está $STATUS"
  degradedPerformance: "⚠️ $SITE_NAME com performance degradada"
  scheduleRecovery: "✅ $SITE_NAME recuperado"
  startIncident: "🚨 Incidente iniciado: $SITE_NAME"
  closeIncident: "✅ Incidente resolvido: $SITE_NAME"

# Intervalo de verificação (em minutos)
workflowSchedule:
  graphs: "0 0 * * *"        # Gráficos: 1x por dia
  responseTime: "0 23 * * *"  # Response time: 1x por dia
  staticSite: "0 1 * * *"     # Site estático: 1x por dia
  summary: "0 0 * * *"        # Sumário: 1x por dia
  updateTemplate: "0 0 * * *" # Template: 1x por dia
  updates: "*/5 * * * *"      # Checks: a cada 5 minutos
  uptime: "*/5 * * * *"       # Uptime: a cada 5 minutos

# Commits automáticos
commitPrefixStatusUp: "✅"
commitPrefixStatusDown: "🚨"
commitPrefixStatusDegraded: "⚠️"

